// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNC016TAp4F4OidnI2rKQLbe60Sb9EGao',
    appId: '1:604729523238:web:b7f17621d0c8bb4d9e7ae7',
    messagingSenderId: '604729523238',
    projectId: 'cine-audio-1aaf1',
    authDomain: 'cine-audio-1aaf1.firebaseapp.com',
    storageBucket: 'cine-audio-1aaf1.firebasestorage.app',
    measurementId: 'G-1BKTJMKBLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5a9GNyxthi_tW1r4P2U7BF8V2dYToYRs',
    appId: '1:604729523238:android:1cf2f8f39e993bf09e7ae7',
    messagingSenderId: '604729523238',
    projectId: 'cine-audio-1aaf1',
    storageBucket: 'cine-audio-1aaf1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDrt63sYhPXsi5liEmaIzPdoUhniQLa0',
    appId: '1:604729523238:ios:ade927ccca3a60ed9e7ae7',
    messagingSenderId: '604729523238',
    projectId: 'cine-audio-1aaf1',
    storageBucket: 'cine-audio-1aaf1.firebasestorage.app',
    iosBundleId: 'com.example.cineAudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNC016TAp4F4OidnI2rKQLbe60Sb9EGao',
    appId: '1:604729523238:web:bdbeb7d575eb48d19e7ae7',
    messagingSenderId: '604729523238',
    projectId: 'cine-audio-1aaf1',
    authDomain: 'cine-audio-1aaf1.firebaseapp.com',
    storageBucket: 'cine-audio-1aaf1.firebasestorage.app',
    measurementId: 'G-0ES5LD8B55',
  );
}
